/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ConsultationBooking {
  'id' : bigint,
  'status' : ConsultationStatus,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'message' : [] | [string],
  'preferredDate' : string,
  'phone' : string,
  'consultationType' : ConsultationType,
}
export type ConsultationStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'confirmed' : null };
export type ConsultationType = { 'investmentAdvice' : null } |
  { 'propertyAssessment' : null } |
  { 'generalInquiry' : null };
export interface MaintenanceSignUp {
  'id' : bigint,
  'status' : MaintenanceStatus,
  'propertyType' : PropertyType,
  'name' : string,
  'createdAt' : bigint,
  'propertyAddress' : string,
  'email' : string,
  'notes' : [] | [string],
  'phone' : string,
}
export type MaintenanceStatus = { 'active' : null } |
  { 'cancelled' : null } |
  { 'pending' : null };
export type PropertyType = { 'commercial' : null } |
  { 'residential' : null } |
  { 'industrial' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllConsultations' : ActorMethod<[], Array<ConsultationBooking>>,
  'getAllMaintenanceSignUps' : ActorMethod<[], Array<MaintenanceSignUp>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitConsultationBooking' : ActorMethod<
    [string, string, string, string, ConsultationType, [] | [string]],
    bigint
  >,
  'submitMaintenanceSignUp' : ActorMethod<
    [string, string, string, string, PropertyType, [] | [string]],
    bigint
  >,
  'updateConsultationStatus' : ActorMethod<
    [bigint, ConsultationStatus],
    undefined
  >,
  'updateMaintenanceStatus' : ActorMethod<
    [bigint, MaintenanceStatus],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];