/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ConsultationStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const ConsultationType = IDL.Variant({
  'investmentAdvice' : IDL.Null,
  'propertyAssessment' : IDL.Null,
  'generalInquiry' : IDL.Null,
});
export const ConsultationBooking = IDL.Record({
  'id' : IDL.Nat,
  'status' : ConsultationStatus,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'message' : IDL.Opt(IDL.Text),
  'preferredDate' : IDL.Text,
  'phone' : IDL.Text,
  'consultationType' : ConsultationType,
});
export const MaintenanceStatus = IDL.Variant({
  'active' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
});
export const PropertyType = IDL.Variant({
  'commercial' : IDL.Null,
  'residential' : IDL.Null,
  'industrial' : IDL.Null,
});
export const MaintenancePlan = IDL.Variant({
  'premium' : IDL.Null,
  'basic' : IDL.Null,
  'standard' : IDL.Null,
});
export const MaintenanceSignUp = IDL.Record({
  'id' : IDL.Nat,
  'status' : MaintenanceStatus,
  'propertyType' : PropertyType,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'propertyAddress' : IDL.Text,
  'email' : IDL.Text,
  'maintenancePlan' : MaintenancePlan,
  'phone' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllConsultations' : IDL.Func(
      [],
      [IDL.Vec(ConsultationBooking)],
      ['query'],
    ),
  'getAllMaintenanceSignUps' : IDL.Func(
      [],
      [IDL.Vec(MaintenanceSignUp)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitConsultationBooking' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        ConsultationType,
        IDL.Opt(IDL.Text),
      ],
      [IDL.Nat],
      [],
    ),
  'submitMaintenanceSignUp' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, PropertyType, MaintenancePlan],
      [IDL.Nat],
      [],
    ),
  'updateConsultationStatus' : IDL.Func([IDL.Nat, ConsultationStatus], [], []),
  'updateMaintenanceStatus' : IDL.Func([IDL.Nat, MaintenanceStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ConsultationStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const ConsultationType = IDL.Variant({
    'investmentAdvice' : IDL.Null,
    'propertyAssessment' : IDL.Null,
    'generalInquiry' : IDL.Null,
  });
  const ConsultationBooking = IDL.Record({
    'id' : IDL.Nat,
    'status' : ConsultationStatus,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'message' : IDL.Opt(IDL.Text),
    'preferredDate' : IDL.Text,
    'phone' : IDL.Text,
    'consultationType' : ConsultationType,
  });
  const MaintenanceStatus = IDL.Variant({
    'active' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
  });
  const PropertyType = IDL.Variant({
    'commercial' : IDL.Null,
    'residential' : IDL.Null,
    'industrial' : IDL.Null,
  });
  const MaintenancePlan = IDL.Variant({
    'premium' : IDL.Null,
    'basic' : IDL.Null,
    'standard' : IDL.Null,
  });
  const MaintenanceSignUp = IDL.Record({
    'id' : IDL.Nat,
    'status' : MaintenanceStatus,
    'propertyType' : PropertyType,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'propertyAddress' : IDL.Text,
    'email' : IDL.Text,
    'maintenancePlan' : MaintenancePlan,
    'phone' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllConsultations' : IDL.Func(
        [],
        [IDL.Vec(ConsultationBooking)],
        ['query'],
      ),
    'getAllMaintenanceSignUps' : IDL.Func(
        [],
        [IDL.Vec(MaintenanceSignUp)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitConsultationBooking' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          ConsultationType,
          IDL.Opt(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
    'submitMaintenanceSignUp' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, PropertyType, MaintenancePlan],
        [IDL.Nat],
        [],
      ),
    'updateConsultationStatus' : IDL.Func(
        [IDL.Nat, ConsultationStatus],
        [],
        [],
      ),
    'updateMaintenanceStatus' : IDL.Func([IDL.Nat, MaintenanceStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };