/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ConsultationBooking {
    id: bigint;
    status: ConsultationStatus;
    name: string;
    createdAt: bigint;
    email: string;
    message?: string;
    preferredDate: string;
    phone: string;
    consultationType: ConsultationType;
}
export interface MaintenanceSignUp {
    id: bigint;
    status: MaintenanceStatus;
    propertyType: PropertyType;
    name: string;
    createdAt: bigint;
    propertyAddress: string;
    email: string;
    maintenancePlan: MaintenancePlan;
    phone: string;
}
export interface UserProfile {
    name: string;
}
export enum ConsultationStatus {
    cancelled = "cancelled",
    pending = "pending",
    completed = "completed",
    confirmed = "confirmed"
}
export enum ConsultationType {
    investmentAdvice = "investmentAdvice",
    propertyAssessment = "propertyAssessment",
    generalInquiry = "generalInquiry"
}
export enum MaintenancePlan {
    premium = "premium",
    basic = "basic",
    standard = "standard"
}
export enum MaintenanceStatus {
    active = "active",
    cancelled = "cancelled",
    pending = "pending"
}
export enum PropertyType {
    commercial = "commercial",
    residential = "residential",
    industrial = "industrial"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getAllConsultations(): Promise<Array<ConsultationBooking>>;
    getAllMaintenanceSignUps(): Promise<Array<MaintenanceSignUp>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitConsultationBooking(name: string, email: string, phone: string, preferredDate: string, consultationType: ConsultationType, message: string | null): Promise<bigint>;
    submitMaintenanceSignUp(name: string, email: string, phone: string, propertyAddress: string, propertyType: PropertyType, maintenancePlan: MaintenancePlan): Promise<bigint>;
    updateConsultationStatus(id: bigint, status: ConsultationStatus): Promise<void>;
    updateMaintenanceStatus(id: bigint, status: MaintenanceStatus): Promise<void>;
}
import type { ConsultationBooking as _ConsultationBooking, ConsultationStatus as _ConsultationStatus, ConsultationType as _ConsultationType, MaintenancePlan as _MaintenancePlan, MaintenanceSignUp as _MaintenanceSignUp, MaintenanceStatus as _MaintenanceStatus, PropertyType as _PropertyType, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAllConsultations(): Promise<Array<ConsultationBooking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllConsultations();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllConsultations();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMaintenanceSignUps(): Promise<Array<MaintenanceSignUp>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMaintenanceSignUps();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMaintenanceSignUps();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitConsultationBooking(arg0: string, arg1: string, arg2: string, arg3: string, arg4: ConsultationType, arg5: string | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitConsultationBooking(arg0, arg1, arg2, arg3, to_candid_ConsultationType_n23(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitConsultationBooking(arg0, arg1, arg2, arg3, to_candid_ConsultationType_n23(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async submitMaintenanceSignUp(arg0: string, arg1: string, arg2: string, arg3: string, arg4: PropertyType, arg5: MaintenancePlan): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitMaintenanceSignUp(arg0, arg1, arg2, arg3, to_candid_PropertyType_n26(this._uploadFile, this._downloadFile, arg4), to_candid_MaintenancePlan_n28(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitMaintenanceSignUp(arg0, arg1, arg2, arg3, to_candid_PropertyType_n26(this._uploadFile, this._downloadFile, arg4), to_candid_MaintenancePlan_n28(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async updateConsultationStatus(arg0: bigint, arg1: ConsultationStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateConsultationStatus(arg0, to_candid_ConsultationStatus_n30(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateConsultationStatus(arg0, to_candid_ConsultationStatus_n30(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateMaintenanceStatus(arg0: bigint, arg1: MaintenanceStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMaintenanceStatus(arg0, to_candid_MaintenanceStatus_n32(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMaintenanceStatus(arg0, to_candid_MaintenanceStatus_n32(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_ConsultationBooking_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ConsultationBooking): ConsultationBooking {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_ConsultationStatus_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ConsultationStatus): ConsultationStatus {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_ConsultationType_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ConsultationType): ConsultationType {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_MaintenancePlan_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MaintenancePlan): MaintenancePlan {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_MaintenanceSignUp_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MaintenanceSignUp): MaintenanceSignUp {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_MaintenanceStatus_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MaintenanceStatus): MaintenanceStatus {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_PropertyType_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PropertyType): PropertyType {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _MaintenanceStatus;
    propertyType: _PropertyType;
    name: string;
    createdAt: bigint;
    propertyAddress: string;
    email: string;
    maintenancePlan: _MaintenancePlan;
    phone: string;
}): {
    id: bigint;
    status: MaintenanceStatus;
    propertyType: PropertyType;
    name: string;
    createdAt: bigint;
    propertyAddress: string;
    email: string;
    maintenancePlan: MaintenancePlan;
    phone: string;
} {
    return {
        id: value.id,
        status: from_candid_MaintenanceStatus_n14(_uploadFile, _downloadFile, value.status),
        propertyType: from_candid_PropertyType_n16(_uploadFile, _downloadFile, value.propertyType),
        name: value.name,
        createdAt: value.createdAt,
        propertyAddress: value.propertyAddress,
        email: value.email,
        maintenancePlan: from_candid_MaintenancePlan_n18(_uploadFile, _downloadFile, value.maintenancePlan),
        phone: value.phone
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _ConsultationStatus;
    name: string;
    createdAt: bigint;
    email: string;
    message: [] | [string];
    preferredDate: string;
    phone: string;
    consultationType: _ConsultationType;
}): {
    id: bigint;
    status: ConsultationStatus;
    name: string;
    createdAt: bigint;
    email: string;
    message?: string;
    preferredDate: string;
    phone: string;
    consultationType: ConsultationType;
} {
    return {
        id: value.id,
        status: from_candid_ConsultationStatus_n6(_uploadFile, _downloadFile, value.status),
        name: value.name,
        createdAt: value.createdAt,
        email: value.email,
        message: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.message)),
        preferredDate: value.preferredDate,
        phone: value.phone,
        consultationType: from_candid_ConsultationType_n9(_uploadFile, _downloadFile, value.consultationType)
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    investmentAdvice: null;
} | {
    propertyAssessment: null;
} | {
    generalInquiry: null;
}): ConsultationType {
    return "investmentAdvice" in value ? ConsultationType.investmentAdvice : "propertyAssessment" in value ? ConsultationType.propertyAssessment : "generalInquiry" in value ? ConsultationType.generalInquiry : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    cancelled: null;
} | {
    pending: null;
}): MaintenanceStatus {
    return "active" in value ? MaintenanceStatus.active : "cancelled" in value ? MaintenanceStatus.cancelled : "pending" in value ? MaintenanceStatus.pending : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    commercial: null;
} | {
    residential: null;
} | {
    industrial: null;
}): PropertyType {
    return "commercial" in value ? PropertyType.commercial : "residential" in value ? PropertyType.residential : "industrial" in value ? PropertyType.industrial : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    premium: null;
} | {
    basic: null;
} | {
    standard: null;
}): MaintenancePlan {
    return "premium" in value ? MaintenancePlan.premium : "basic" in value ? MaintenancePlan.basic : "standard" in value ? MaintenancePlan.standard : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    confirmed: null;
}): ConsultationStatus {
    return "cancelled" in value ? ConsultationStatus.cancelled : "pending" in value ? ConsultationStatus.pending : "completed" in value ? ConsultationStatus.completed : "confirmed" in value ? ConsultationStatus.confirmed : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MaintenanceSignUp>): Array<MaintenanceSignUp> {
    return value.map((x)=>from_candid_MaintenanceSignUp_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ConsultationBooking>): Array<ConsultationBooking> {
    return value.map((x)=>from_candid_ConsultationBooking_n4(_uploadFile, _downloadFile, x));
}
function to_candid_ConsultationStatus_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ConsultationStatus): _ConsultationStatus {
    return to_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function to_candid_ConsultationType_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ConsultationType): _ConsultationType {
    return to_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function to_candid_MaintenancePlan_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MaintenancePlan): _MaintenancePlan {
    return to_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function to_candid_MaintenanceStatus_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MaintenanceStatus): _MaintenanceStatus {
    return to_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function to_candid_PropertyType_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertyType): _PropertyType {
    return to_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ConsultationType): {
    investmentAdvice: null;
} | {
    propertyAssessment: null;
} | {
    generalInquiry: null;
} {
    return value == ConsultationType.investmentAdvice ? {
        investmentAdvice: null
    } : value == ConsultationType.propertyAssessment ? {
        propertyAssessment: null
    } : value == ConsultationType.generalInquiry ? {
        generalInquiry: null
    } : value;
}
function to_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertyType): {
    commercial: null;
} | {
    residential: null;
} | {
    industrial: null;
} {
    return value == PropertyType.commercial ? {
        commercial: null
    } : value == PropertyType.residential ? {
        residential: null
    } : value == PropertyType.industrial ? {
        industrial: null
    } : value;
}
function to_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MaintenancePlan): {
    premium: null;
} | {
    basic: null;
} | {
    standard: null;
} {
    return value == MaintenancePlan.premium ? {
        premium: null
    } : value == MaintenancePlan.basic ? {
        basic: null
    } : value == MaintenancePlan.standard ? {
        standard: null
    } : value;
}
function to_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ConsultationStatus): {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    confirmed: null;
} {
    return value == ConsultationStatus.cancelled ? {
        cancelled: null
    } : value == ConsultationStatus.pending ? {
        pending: null
    } : value == ConsultationStatus.completed ? {
        completed: null
    } : value == ConsultationStatus.confirmed ? {
        confirmed: null
    } : value;
}
function to_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MaintenanceStatus): {
    active: null;
} | {
    cancelled: null;
} | {
    pending: null;
} {
    return value == MaintenanceStatus.active ? {
        active: null
    } : value == MaintenanceStatus.cancelled ? {
        cancelled: null
    } : value == MaintenanceStatus.pending ? {
        pending: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
